# Generated by Django 4.2.1 on 2023-06-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_s', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(max_length=80)),
                ('tipo_cliente', models.CharField(max_length=80)),
                ('rut', models.CharField(max_length=16)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=80)),
                ('CantHoras', models.IntegerField()),
                ('PrecioHora', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('nombre_s', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.servicio')),
            ],
        ),
    ]
